services:
  webapp:
    image: shop-planr:latest
    container_name: shop-planr
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
